In [5]:
test = "Vol.87 Chapter 105 test"
display(test.find('Chapter'))
display(test.split(' '))

7

['Vol.87', 'Chapter', '105', 'test']

In [13]:
import os
def get_dic(Name_path,):  
    chapt_list = os.listdir("/Volumes/222EXT/222Mangas_input/20th Century Boys")
    #chapt_list = os.listdir("/Volumes/222EXT/222Mangas_input/GTO")
    nul = [".DS_Store", "._.DS_Store"]
    for ele in nul:
        try:
            chapt_list.remove(ele)
        except:
            pass
    spe_dic={}
    for el in chapt_list:
        if Name_path=='Vagabond':
            chapt = round(float(el.split(' ')[2]))
        else:
            chapt = round(float(el.split(' ')[1].split('.')[1]))  #<Vol.XX Chapter.XX>
        try:
            vol = round(float(el.split(' ')[0].split('.')[1]))
        except:
            print(el, "error")
        print(chapt,vol)
        spe_dic[chapt]=vol
    return spe_dic

In [1]:
import re

a1 = "Ch.177.3"
a2 = "Chapter 177.3"
a3 = "Vol.3 Ch.177.3"
a4 = "Vol.3 Chapter 177.3 test"

In [2]:
x = a4
try:
    y = re.search(r'Chapter \d+',x).group(0)
except:
    y = re.search(r'Ch.\d+',x).group(0)
re.findall(r'\d+',y)[0]

'177'

In [8]:
y = re.search(r'Vol.\d+',x).group()
re.findall(r'\d+',y)[0]

'3'

In [57]:
import pandas as pd
import numpy as np
df = pd.read_excel('new.xlsx', sheet_name='UPDATE')

In [59]:
manga = "SakDays"
sub = df[["Vol",manga]].copy()
sub = sub.dropna()
dic = pd.Series(sub.Vol.values, index=sub[manga])
dic.index = dic.index.astype("int")

In [45]:
dic

SakDays
124    TBD
106     12
97      11
88      10
79       9
70       8
61       7
52       6
43       5
34       4
25       3
16       2
7        1
dtype: object

In [60]:
d = {}
l = list(dic.index)
l.reverse()

for j in range(l[0]+1):
    d[j] = dic[l[0]]
for k in range(1,len(l)):
    for j in range(l[k-1],l[k]+1):
        d[j] = dic[l[k]]

d

{0: 1,
 1: 1,
 2: 1,
 3: 1,
 4: 1,
 5: 1,
 6: 1,
 7: 2,
 8: 2,
 9: 2,
 10: 2,
 11: 2,
 12: 2,
 13: 2,
 14: 2,
 15: 2,
 16: 3,
 17: 3,
 18: 3,
 19: 3,
 20: 3,
 21: 3,
 22: 3,
 23: 3,
 24: 3,
 25: 4,
 26: 4,
 27: 4,
 28: 4,
 29: 4,
 30: 4,
 31: 4,
 32: 4,
 33: 4,
 34: 5,
 35: 5,
 36: 5,
 37: 5,
 38: 5,
 39: 5,
 40: 5,
 41: 5,
 42: 5,
 43: 6,
 44: 6,
 45: 6,
 46: 6,
 47: 6,
 48: 6,
 49: 6,
 50: 6,
 51: 6,
 52: 7,
 53: 7,
 54: 7,
 55: 7,
 56: 7,
 57: 7,
 58: 7,
 59: 7,
 60: 7,
 61: 8,
 62: 8,
 63: 8,
 64: 8,
 65: 8,
 66: 8,
 67: 8,
 68: 8,
 69: 8,
 70: 9,
 71: 9,
 72: 9,
 73: 9,
 74: 9,
 75: 9,
 76: 9,
 77: 9,
 78: 9,
 79: 10,
 80: 10,
 81: 10,
 82: 10,
 83: 10,
 84: 10,
 85: 10,
 86: 10,
 87: 10,
 88: 11,
 89: 11,
 90: 11,
 91: 11,
 92: 11,
 93: 11,
 94: 11,
 95: 11,
 96: 11,
 97: 12,
 98: 12,
 99: 12,
 100: 12,
 101: 12,
 102: 12,
 103: 12,
 104: 12,
 105: 12,
 106: 'TBD',
 107: 'TBD',
 108: 'TBD',
 109: 'TBD',
 110: 'TBD',
 111: 'TBD',
 112: 'TBD',
 113: 'TBD',
 114: 'TBD',
 115: 'TBD',

In [61]:
d.keys()

dict_keys([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124])

In [1]:
import pandas as pd 

In [19]:
f = pd.read_excel("/Users/prld/git/EMS/origin.xlsx", sheet_name="SETTINGS",usecols="A:B")
dict(zip(f.Manga, f.Manga_path))

{'20thCB': '20th Century Boys',
 'BCL': 'Black Clover',
 'Bleach': 'Bleach',
 'Chainsaw': 'Chainsaw Man',
 'CJX': 'Choujin X',
 'Conan': 'Detective Conan',
 'DB': 'Dragon Ball',
 'DBSuper': 'Dragon Ball Super',
 'Gamaran': 'Gamaran',
 'Gintama': 'Gintama',
 'GTO': 'GTO',
 'HellP': "Hell's Paradise Jigokuraku",
 'HxH': 'Hunter X Hunter',
 'JJK': 'Jujutsu Kaisen',
 'Jojo1': 'JoJo’s Bizarre Adventure',
 'Jojo2': 'JoJo’s Bizarre Adventure',
 'Jojo3': 'JoJo’s Bizarre Adventure',
 'Jojo4': 'Jojo’s Bizarre Adventure Part 8 – Jojolion',
 'Kaiju': 'Kaiju No. 8',
 'KNB': 'Kuroko no Basuke',
 'Mashle': 'Mashle',
 'MHA': 'Boku no Hero Academia',
 'NNTZ': 'Nanatsu no Taizai',
 'OP': 'One Piece',
 'Opman': 'Onepunch-Man',
 'SakDays': 'Sakamoto Days',
 'SKR': 'Sun-ken Rock',
 'SNK': 'Shingeki no Kyojin',
 'SpyF': 'Spy X Family',
 'SSY Lost Canva': 'Saint Seiya - The Lost Canva',
 'TK': 'Tokyo Ghoul',
 'TKre': 'Tokyo Ghoulre',
 'Vagabond': 'Vagabond',
 'Vinland': 'Vinland Saga',
 'YuGiOh': 'Yu-Gi-Oh !

In [20]:
import re
import pandas as pd
import openpyxl
import sys
a = "Vol.1 Chapter 10  Shinmen Takezo"
b = "Vol.03 Ch.021 - Select"

In [12]:
def f(el):
    try:
        y = re.search(r'Chapter \d+',el).group(0)
    except:
        y = re.search(r'Ch.\d+',el).group(0)
    num = round(float(re.findall(r'\d+',y)[0]))
    vol = round(float(re.findall(r'\d+',re.search(r'Vol.\d+',el).group(0))[0]))
    return(vol,num)

In [102]:
g = pd.read_excel("/Users/prld/git/EMS/origin.xlsx", sheet_name="update_copy",usecols="A")
g["xl_rows"] = [k for k in range(2,len(g)+2)]
g = g.set_index("Vol",drop=True)
print(sys.getsizeof(g))
display(g)

5848


xl_rows
Vol         
TBD        2
131        3
130        4
129        5
128        6
..       ...
5        129
4        130
3        131
2        132
1        133

[132 rows x 1 columns]

In [101]:
g = g[["xl_rows","MHA"]].copy()
display(g)
print(sys.getsizeof(g))

xl_rows    MHA
Vol                
TBD        2  395.0
131        3    NaN
130        4    NaN
129        5    NaN
128        6    NaN
..       ...    ...
5        129   44.0
4        130   35.0
3        131   26.0
2        132   17.0
1        133    7.0

[132 rows x 2 columns]

6904


In [91]:
test.loc[18]["xl_rows"]

116.0

In [63]:
workbook = openpyxl.load_workbook('/Users/prld/git/EMS/origin.xlsx')
sheet = workbook["update_copy"]

In [64]:
ml = [c.value for c in sheet["1"] if c.value != None]
ml

['Vol',
 'BCL',
 'SakDays',
 'Conan',
 'JJK',
 'MHA',
 'CJX',
 'HxH',
 'OP',
 'Chainsaw',
 'Opman',
 'Mashle',
 'SpyF',
 'DBSuper',
 'Tablier',
 'Jojo1',
 'Jojo2',
 'Jojo3',
 'Jojo4',
 'YuGiOh',
 'NNTZ',
 'SNK',
 'KNB',
 'DB',
 'Bleach',
 'Gintama',
 'Gamaran',
 'HellP',
 'Mob100',
 'Immortal',
 'Fable',
 'Monster']

In [68]:
sheet.cell(row=3,column=2).value = 12
workbook.save('origin.xlsx')

In [78]:
ml

['Vol',
 'BCL',
 'SakDays',
 'Conan',
 'JJK',
 'MHA',
 'CJX',
 'HxH',
 'OP',
 'Chainsaw',
 'Opman',
 'Mashle',
 'SpyF',
 'DBSuper',
 'Tablier',
 'Jojo1',
 'Jojo2',
 'Jojo3',
 'Jojo4',
 'YuGiOh',
 'NNTZ',
 'SNK',
 'KNB',
 'DB',
 'Bleach',
 'Gintama',
 'Gamaran',
 'HellP',
 'Mob100',
 'Immortal',
 'Fable',
 'Monster']

In [106]:
pd_wb = pd.read_excel("origin.xlsx", sheet_name="update_copy",usecols="A")
pd_wb["xl_rows"] = [k for k in range(2,len(pd_wb)+2)]
pd_wb = pd_wb.set_index("Vol",drop=True)
pd_wb.to_dict()["xl_rows"]

{'TBD': 2,
 131: 3,
 130: 4,
 129: 5,
 128: 6,
 127: 7,
 126: 8,
 125: 9,
 124: 10,
 123: 11,
 122: 12,
 121: 13,
 120: 14,
 119: 15,
 118: 16,
 117: 17,
 116: 18,
 115: 19,
 114: 20,
 113: 21,
 112: 22,
 111: 23,
 110: 24,
 109: 25,
 108: 26,
 107: 27,
 106: 28,
 105: 29,
 104: 30,
 103: 31,
 102: 32,
 101: 33,
 100: 34,
 99: 35,
 98: 36,
 97: 37,
 96: 38,
 95: 39,
 94: 40,
 93: 41,
 92: 42,
 91: 43,
 90: 44,
 89: 45,
 88: 46,
 87: 47,
 86: 48,
 85: 49,
 84: 50,
 83: 51,
 82: 52,
 81: 53,
 80: 54,
 79: 55,
 78: 56,
 77: 57,
 76: 58,
 75: 59,
 74: 60,
 73: 61,
 72: 62,
 71: 63,
 70: 64,
 69: 65,
 68: 66,
 67: 67,
 66: 68,
 65: 69,
 64: 70,
 63: 71,
 62: 72,
 61: 73,
 60: 74,
 59: 75,
 58: 76,
 57: 77,
 56: 78,
 55: 79,
 54: 80,
 53: 81,
 52: 82,
 51: 83,
 50: 84,
 49: 85,
 48: 86,
 47: 87,
 46: 88,
 45: 89,
 44: 90,
 43: 91,
 42: 92,
 41: 93,
 40: 94,
 39: 95,
 38: 96,
 37: 97,
 36: 98,
 35: 99,
 34: 100,
 33: 101,
 32: 102,
 31: 103,
 30: 104,
 29: 105,
 28: 106,
 27: 107,
 26: 108,
 

In [14]:
import pandas as pd
pd_wb = pd.read_excel("origin.xlsx", sheet_name="UPDATE",usecols="A")
pd_wb["xl_rows"] = [k for k in range(2,len(pd_wb)+2)]
pd_wb = pd_wb.set_index("Vol",drop=True)
pd_wb = pd_wb.to_dict()["xl_rows"]
pd_wb

{'TBD': 2,
 131: 3,
 130: 4,
 129: 5,
 128: 6,
 127: 7,
 126: 8,
 125: 9,
 124: 10,
 123: 11,
 122: 12,
 121: 13,
 120: 14,
 119: 15,
 118: 16,
 117: 17,
 116: 18,
 115: 19,
 114: 20,
 113: 21,
 112: 22,
 111: 23,
 110: 24,
 109: 25,
 108: 26,
 107: 27,
 106: 28,
 105: 29,
 104: 30,
 103: 31,
 102: 32,
 101: 33,
 100: 34,
 99: 35,
 98: 36,
 97: 37,
 96: 38,
 95: 39,
 94: 40,
 93: 41,
 92: 42,
 91: 43,
 90: 44,
 89: 45,
 88: 46,
 87: 47,
 86: 48,
 85: 49,
 84: 50,
 83: 51,
 82: 52,
 81: 53,
 80: 54,
 79: 55,
 78: 56,
 77: 57,
 76: 58,
 75: 59,
 74: 60,
 73: 61,
 72: 62,
 71: 63,
 70: 64,
 69: 65,
 68: 66,
 67: 67,
 66: 68,
 65: 69,
 64: 70,
 63: 71,
 62: 72,
 61: 73,
 60: 74,
 59: 75,
 58: 76,
 57: 77,
 56: 78,
 55: 79,
 54: 80,
 53: 81,
 52: 82,
 51: 83,
 50: 84,
 49: 85,
 48: 86,
 47: 87,
 46: 88,
 45: 89,
 44: 90,
 43: 91,
 42: 92,
 41: 93,
 40: 94,
 39: 95,
 38: 96,
 37: 97,
 36: 98,
 35: 99,
 34: 100,
 33: 101,
 32: 102,
 31: 103,
 30: 104,
 29: 105,
 28: 106,
 27: 107,
 26: 108,
 

In [24]:
tex = 'Episode 12'
hk_chapt_name = ['Page','Kapitel','Lesson','Level','Episode']

def f(el):
    try:
        y = re.search(r'Chapter \d+',el).group(0)
    except:
        try:
            y = re.search(r'Ch.\d+',el).group(0)
        except:
            for x in hk_chapt_name:
                try:
                    var = x + ' \d+'
                    y = re.search(var,el).group(0)
                except:
                    pass
    return y

In [25]:
f(tex)

'Episode 12'

In [30]:
import openpyxl
import pandas as pd
wb = openpyxl.load_workbook('/Users/prld/git/EMS/origin.xlsx')
ws = wb["UPDATE"]
ml = [c.value for c in ws["1"] if c.value != None]
col_n = ml.index('Berserk')+1
col_n

38

In [72]:
chr(64+26)

'Z'

In [70]:
(43-(43%26))/26

1.0

In [69]:
43%26

17

In [75]:
def excel_col_str(x):
    if x==0:
        return()
    if 1<=x<=26:
        return chr(64+x)
    r = int(x%26)
    k = int((x-r)/26)
    if r==0:
        r=26
        k-=1
        return excel_col_str(k)+'Z'
    else:
        return excel_col_str(k)+excel_col_str(r)

In [79]:
excel_col_str(1)

'A'

In [29]:
converted = '/Volumes/222EXT/Converted/'
def check_dispo():
    dispo = []
    for el in os.listdir(converted):
        if ('Complete' in el) == False:
            dispo.append(el.split(' ',1)[1])
        else:
            dispo.append(el.split('Complete - ')[1])
    dispo.sort()
    return dispo
check_dispo()

['20th Century Boys',
 'BCL',
 'Bleach',
 'CJX',
 'Chainsaw',
 'Conan',
 'DB',
 'DBSuper',
 'GTO',
 'Gintama',
 'HxH',
 'Immortal',
 'JJK',
 'Jojo1',
 'KNB',
 'Kaiju8',
 'MHA',
 'Mashle',
 'NNTZ',
 'OP',
 'SNK',
 'SakDays',
 'Vagabond',
 'YuGiOh']

In [37]:
hk_chapt_name = ['Page','Days','Kapitel','Lesson','Level','Episode','No.', 'Quarter', "#", "Prologue", "Class", "Z="]
chapt = os.listdir('/Volumes/222EXT/222Mangas_input/Sakamoto Days')[12]
try:
    y = re.search(r'Chapter \d+',chapt).group(0)
except:
    try:
        y = re.search(r'Ch.\d+',chapt).group(0)
    except:
        # Format MangaSee ...
        iterr = True
        c = 0
        while iterr == True:
            x = hk_chapt_name[c]
            try:
                var = x + ' \d+'
                y = re.search(var,chapt).group(0)
                iterr = False
            except:
                c+=1
                pass
num = re.findall(r'\d+',y)[0]
num

'119'

In [43]:
import pandas as pd
f = pd.read_excel("/Users/prld/git/EMS/origin.xlsx", sheet_name="SETTINGS",usecols="O,N,H")
df = f[f['up.py']==True][['edit_name']]
df_tbd = f[f['up.py']==True][['edit_name','TBD']]
#df.sort_values('edit_name',inplace=True)
#manga_list = df['edit_name'].to_list()
df_tbd.set_index('edit_name',drop=True,inplace=True)
df_tbd

TBD
edit_name                          
20th Century Boys             False
Assassination Classroom       False
Black Clover                   True
Berserk                        True
Berserk prologue              False
Bleach                        False
Blue Lock                      True
Chainsaw Man                   True
Choujin X                      True
Detective Conan                True
Dragon Ball                   False
Dragon Ball Super              True
Gamaran                       False
Gintama                       False
GTO                           False
Hell's Paradise               False
Hunter X Hunter                True
Blade of the Immortal         False
Jujutsu Kaisen                 True
JoJo 1                        False
JoJo 2                        False
JoJo 3                        False
Jojo 4                        False
Kaiju No. 8                    True
Kuroko no Basket              False
Mashle                         True
My Hero Academia               True
Mob Psycho 100                False
Monster                       False
Montage                       False
Moriarty                      False
Nanatsu no Taizai             False
One Piece                      True
Onepunch Man                   True
Sakamoto Days                  True
Sidooh                        False
Sun-ken Rock                  False
Shingeki no Kyojin            False
Spy X Family                   True
The Way of the House Husband  False
Tokyo Ghoul                   False
Tokyo Ghoulre                 False
Vagabond                      False
Yu-Gi-Oh                      False

In [60]:
fold = [x for x in os.listdir(converted) if 'SakDays' in x][-1]
display(converted+fold)
#os.remove(converted+fold+"/"+'CJX'+" VolTBD.cbz")

'/Volumes/222EXT/Converted/2023-07-7 SakDays'

In [62]:
from shutil import move
move("/Volumes/222EXT/222Mangas_output/2023-08-16_2 SakDays/SakDays VolTBD.zip",converted+fold+"/"+"SakDays"+" VolTBD.zip")

'/Volumes/222EXT/Converted/2023-07-7 SakDays/SakDays VolTBD.zip'

In [49]:
os.listdir("/Volumes/222EXT/Converted/2023-06-30_1 BCL")

['BCL Vol26.cbz',
 'BCL Vol27.cbz',
 'BCL Vol28.cbz',
 'BCL Vol29.cbz',
 'BCL Vol30.cbz',
 'BCL Vol31.cbz',
 'BCL Vol32.cbz',
 'BCL Vol33.cbz',
 'BCL Vol34.cbz',
 'BCL Vol35.cbz',
 'BCL VolTBD.cbz']

In [50]:
os.listdir('/Volumes/222EXT/222Mangas_output/2023-08-16_3 Chainsaw')

['Chainsaw VolTBD.zip']

In [63]:
from shutil import rmtree, move
def tbd_replace(manga,pth):
    fold = [x for x in os.listdir(converted) if manga in x][0]
    try:os.remove(converted+fold+"/"+manga+" VolTBD.cbz")
    except:pass
    move(pth+'/'+manga+' VolTBD.zip',converted+fold+"/"+manga+" VolTBD.zip")
    rmtree(pth,ignore_errors=True)

In [64]:
tbd_replace(manga="SakDays",pth="/Volumes/222EXT/222Mangas_output/2023-08-16_1 SakDays")

------

In [2]:
from main.zp_cover import *
import os

In [ ]:
op = "https://comicvine.gamespot.com/one-piece/4050-21397/"

In [11]:
covs = [ el for el in os.listdir("/Volumes/222EXT/222Covers/OP") if '._' not in el ]
display(len(covs)-('.DS_Store' in covs)-('TBD.jpg' in covs)-('0.jpg' in covs))

106

In [14]:
('0.jpg' in covs)

True

------

In [3]:
import pandas as pd
df = pd.read_excel('origin.xlsx', sheet_name='UPDATE')
sub = df[["Vol",'Jojo2']].copy()
sub.dropna()

Vol  Jojo2
52  80  752.0
53  79  740.0
54  78  729.0
55  77  720.0
56  76  711.0
57  75  702.0
58  74  693.0
59  73  684.0
60  72  675.0
61  71  666.0
62  70  657.0
63  69  648.0
64  68  639.0
65  67  630.0
66  66  621.0
67  65  611.0
68  64  602.0

In [13]:
def test(xlsx, Name):
    df = pd.read_excel(xlsx, sheet_name='UPDATE')
    sub = df[["Vol",Name]].copy()
    sub = sub.dropna()
    sub_dic = pd.Series(sub.Vol.values, index=sub[Name])
    sub_dic.index = sub_dic.index.astype("int")
    df_dic = {}
    l = list(sub_dic.index)
    l.reverse()
    
    #print(l)
    if l[0]<20: #ex Berserk, Jojo4 ... ça doit marcher avec ce code là et pas l'autre
        for j in range(l[0]+1):
            df_dic[j] = sub_dic[l[0]]
        for k in range(1,len(l)):
            for j in range(l[k-1]+1,l[k]+1):
                df_dic[j] = sub_dic[l[k]]
        return df_dic
    else:   # CF Jojo1, Jojo2 etc...
        for j in range(l[0]+1,l[1]+1):
            df_dic[j] = sub_dic[l[0]]
        for k in range(1,len(l)):
            for j in range(l[k-1]+1,l[k]+1):
                df_dic[j] = sub_dic[l[k]]
        return df_dic
        
test('origin.xlsx','Jojo2')

[594, 602, 611, 621, 630, 639, 648, 657, 666, 675, 684, 693, 702, 711, 720, 729, 740, 752]


{595: 64,
 596: 64,
 597: 64,
 598: 64,
 599: 64,
 600: 64,
 601: 64,
 602: 64,
 603: 65,
 604: 65,
 605: 65,
 606: 65,
 607: 65,
 608: 65,
 609: 65,
 610: 65,
 611: 65,
 612: 66,
 613: 66,
 614: 66,
 615: 66,
 616: 66,
 617: 66,
 618: 66,
 619: 66,
 620: 66,
 621: 66,
 622: 67,
 623: 67,
 624: 67,
 625: 67,
 626: 67,
 627: 67,
 628: 67,
 629: 67,
 630: 67,
 631: 68,
 632: 68,
 633: 68,
 634: 68,
 635: 68,
 636: 68,
 637: 68,
 638: 68,
 639: 68,
 640: 69,
 641: 69,
 642: 69,
 643: 69,
 644: 69,
 645: 69,
 646: 69,
 647: 69,
 648: 69,
 649: 70,
 650: 70,
 651: 70,
 652: 70,
 653: 70,
 654: 70,
 655: 70,
 656: 70,
 657: 70,
 658: 71,
 659: 71,
 660: 71,
 661: 71,
 662: 71,
 663: 71,
 664: 71,
 665: 71,
 666: 71,
 667: 72,
 668: 72,
 669: 72,
 670: 72,
 671: 72,
 672: 72,
 673: 72,
 674: 72,
 675: 72,
 676: 73,
 677: 73,
 678: 73,
 679: 73,
 680: 73,
 681: 73,
 682: 73,
 683: 73,
 684: 73,
 685: 74,
 686: 74,
 687: 74,
 688: 74,
 689: 74,
 690: 74,
 691: 74,
 692: 74,
 693: 74,
 694: 75,


In [15]:
pd.read_excel('origin.xlsx', sheet_name='UPDATE')

Vol    BCL  SakDays   Conan    JJK    MHA   CJX    HxH      OP  Chainsaw  \
0    TBD  367.0    129.0  1115.0  230.0  395.0  40.0  400.0  1080.0     138.0   
1    131    NaN      NaN     NaN    NaN    NaN   NaN    NaN     NaN       NaN   
2    130    NaN      NaN     NaN    NaN    NaN   NaN    NaN     NaN       NaN   
3    129    NaN      NaN     NaN    NaN    NaN   NaN    NaN     NaN       NaN   
4    128    NaN      NaN     NaN    NaN    NaN   NaN    NaN     NaN       NaN   
..   ...    ...      ...     ...    ...    ...   ...    ...     ...       ...   
127    5   44.0     43.0    50.0   43.0   44.0  33.0   44.0    44.0      43.0   
128    4   34.0     34.0    39.0   34.0   35.0  27.0   35.0    35.0      34.0   
129    3   25.0     25.0    29.0   25.0   26.0  21.0   26.0    26.0      25.0   
130    2   16.0     16.0    19.0   16.0   17.0  15.0   17.0    17.0      16.0   
131    1    7.0      7.0     9.0    7.0    7.0   6.0    8.0     8.0       7.0   

     ...  Gantz  Montage  Issak  Assassination Classroom  Moriarty  Berserk  \
0    ...    NaN      NaN    NaN                      NaN       NaN    373.0   
1    ...    NaN      NaN    NaN                      NaN       NaN      NaN   
2    ...    NaN      NaN    NaN                      NaN       NaN      NaN   
3    ...    NaN      NaN    NaN                      NaN       NaN      NaN   
4    ...    NaN      NaN    NaN                      NaN       NaN      NaN   
..   ...    ...      ...    ...                      ...       ...      ...   
127  ...   58.0     48.0   21.0                     43.0      19.0      6.0   
128  ...   46.0     38.0   16.0                     34.0      15.0      NaN   
129  ...   34.0     28.0   11.0                     25.0      11.0      NaN   
130  ...   22.0     18.0    7.0                     16.0       7.0      NaN   
131  ...   10.0      8.0    3.0                      7.0       3.0      NaN   

     Berserk_prologue  Sidooh  Kaiju8  BlueLock  
0                 NaN     NaN    90.0     228.0  
1                 NaN     NaN     NaN       NaN  
2                 NaN     NaN     NaN       NaN  
3                 NaN     NaN     NaN       NaN  
4                 NaN     NaN     NaN       NaN  
..                ...     ...     ...       ...  
127               NaN    51.0    43.0      40.0  
128              16.0    40.0    35.0      31.0  
129               9.0    29.0    26.0      22.0  
130               5.0    18.0    17.0      13.0  
131               3.0     7.0     7.0       4.0  

[132 rows x 42 columns]

In [11]:
display(np.arange(0.01,0.07,0.01))
display(np.arange(0.01,0.08,0.01))
display(np.arange(0.01,0.09,0.01))

array([0.01, 0.02, 0.03, 0.04, 0.05, 0.06])

array([0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08])

array([0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08])

In [12]:
display(np.arange(1,7,1)/100)
display(np.arange(1,8,1)/100)
display(np.arange(1,9,1)/100)

array([0.01, 0.02, 0.03, 0.04, 0.05, 0.06])

array([0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07])

array([0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08])

In [35]:
import os
import pandas as pd
import numpy as np
from math import floor
from shutil import copytree
from tqdm import tqdm
import re
from ems_folder_pth import *
#from main.zp_configure import retrieve_file_paths

#--------------------
def rebaser(df):
    df = df.sort_values(by="num", ignore_index=True)
    df["floor_num"] = df["num"].apply(lambda x: floor(x))
    value_ct = dict(df["floor_num"].value_counts())
    #df["clean_chapt"] = ""                               # ? Sept.23 Depreciation warning `df.iloc[:, i] = newvals` will attempt to set the values inplace instead of always setting a new array.
    for el_ in list(value_ct.keys()):
        mask = (df["floor_num"]==el_)
        long = len(df.loc[mask])
        to_add = pd.Series(np.arange(1,long+1,1)/100).set_axis(df.loc[mask].index)
        df.loc[mask,"clean_chapt"] = df.loc[mask,"floor_num"]+to_add
    return df

def chapt_central(Name_path, dic):
    
    def chapt_search(chapt):
        try:
            #y = re.search(r'Chapter \d+',chapt).group(0)
            y = re.search(r'Chapter ((\d+(\.\d*)?))',chapt).group(0)
        except:
            try:
                y = re.search(r'Ch.((\d+(\.\d*)?))',chapt).group(0)
            except:
                # Format MangaSee ...
                iterr = True
                c = 0
                while iterr == True:
                    x = hk_chapt_name[c]
                    try:
                        var = x + ' ((\d+(\.\d*)?))'
                        y = re.search(var,chapt).group(0)
                        iterr = False
                    except:
                        c+=1
                        pass
        num = float(re.findall(r'((\d+(\.\d*)?))',y)[0][0])
        return num
    
    df = pd.DataFrame({'chapt':[], 'num':[], 'vol':[]})
    i = 0
    input_path = base_path+Name_path
    save_path = clean_path+Name_path+"*"
    
    if os.path.exists(save_path) == False:
        os.mkdir(save_path)
    
    if len(os.listdir(save_path)) == len(os.listdir(input_path)):
        return()
    
    else:
        save_list = []
        
        for chapt in os.listdir(input_path):
            if chapt not in [".DS_Store", "._.DS_Store"]:
                try:
                    num = chapt_search(chapt)
                    try:
                        vol = dic[round(num)]
                        df.loc[i] = [chapt, num, vol]
                        i+=1
                    except:pass
                except:
                    print(chapt)
        #print(df)
        df = rebaser(df)
        return df

In [33]:
manga = 'Opman'
manga_pth = "Onepunch-Man"

from main.ems_main import get_settings, get_dic
xlsx = pd.ExcelFile('origin.xlsx')
set = get_settings(manga, xlsx)
manga_dic = get_dic(manga, set['Manga_path'], xlsx)

In [36]:
chapt_central(manga_pth,manga_dic)

Chapter Extra  Bonus Chapter
Chapter Extra
Vol.19 Bonus Reality Strikes
Vol.tbd Extras
Oneshot Young Jump Special 6


chapt    num  vol  floor_num  clean_chapt
0                   Chapter 1 One Punch    1.0    1          1         1.01
1        Chapter 2 Crab And Job Hunting    2.0    1          2         2.01
2            Chapter 3 Walking Disaster    3.0    1          3         3.01
3    Chapter 4 Subterraneans Of Darknes    4.0    1          4         4.01
4              Chapter 5 Itch Explosion    5.0    1          5         5.01
..                                  ...    ...  ...        ...          ...
268                         Chapter 174  174.0  TBD        174       174.01
269                         Chapter 175  175.0  TBD        175       175.01
270                         Chapter 176  176.0  TBD        176       176.01
271                         Chapter 177  177.0  TBD        177       177.01
272                         Chapter 178  178.0  TBD        178       178.01

[273 rows x 5 columns]

In [2]:
from main.ems_configure import retrieve_file_paths
test = retrieve_file_paths("/Volumes/222EXT/222Mangas_clean/Attack on Titan*")

In [3]:
test

['/Volumes/222EXT/222Mangas_clean/Attack on Titan*/Vol.1 Chapter 1.01/01.jpg',
 '/Volumes/222EXT/222Mangas_clean/Attack on Titan*/Vol.1 Chapter 1.01/02.jpg',
 '/Volumes/222EXT/222Mangas_clean/Attack on Titan*/Vol.1 Chapter 1.01/03.jpg',
 '/Volumes/222EXT/222Mangas_clean/Attack on Titan*/Vol.1 Chapter 1.01/05.jpg',
 '/Volumes/222EXT/222Mangas_clean/Attack on Titan*/Vol.1 Chapter 1.01/14.jpg',
 '/Volumes/222EXT/222Mangas_clean/Attack on Titan*/Vol.1 Chapter 1.01/15.jpg',
 '/Volumes/222EXT/222Mangas_clean/Attack on Titan*/Vol.1 Chapter 1.01/16.jpg',
 '/Volumes/222EXT/222Mangas_clean/Attack on Titan*/Vol.1 Chapter 1.01/18.jpg',
 '/Volumes/222EXT/222Mangas_clean/Attack on Titan*/Vol.1 Chapter 1.01/22.jpg',
 '/Volumes/222EXT/222Mangas_clean/Attack on Titan*/Vol.1 Chapter 1.01/09.jpg',
 '/Volumes/222EXT/222Mangas_clean/Attack on Titan*/Vol.1 Chapter 1.01/19.jpg',
 '/Volumes/222EXT/222Mangas_clean/Attack on Titan*/Vol.1 Chapter 1.01/20.jpg',
 '/Volumes/222EXT/222Mangas_clean/Attack on Titan*/V

In [6]:
el = test[1]
long = len("/Volumes/222EXT/222Mangas_clean/Attack on Titan*")

In [15]:
#round(float(el[long::].split(' ')[1].split(' ')[1].split('/')[0]))
el[long::].split(' ')[2].split('/')[0]

'1.01'